### ISSUE TITLE
questions regarding slidify

### ISSUE THREAD

**Issue by jiakm** [ramnathv/slidify#360]
Hi, I just started to learn this great package 'slidify' and run into some problems.

Firstly, I included interactive plots generated by'rCharts'. Every time that I tried slidify('index.Rmd') and browseURL('index.Rmd'), it gave me an error msg saying that 'Error: object 'opts_current' not found'. Does it mean I have to use 'Knit HTML' instead of slidify?

Secondly, I tried to add a "interactive console". I put 'interactive' in the widgets and "---&interactive", however i didn't see the little buttons below interactive console as shown in the example. Besides, if i use 'Knit HTML', it seems not using interactive as a widget. If i use slidify, the same error came up.

At last, I tried to include the Shiny as the example, like using slidifyUI and app.R. However, the interactive sliderbar didn't show up and neither did the plot. I am wondering, can I define a app function directly in the R chunk instead of specifying ui and serve separately?

Could you give some suggestion on these problems? Really appreciate that.

**Comment by jjesusfilho** [comment]
Hi Ramnathv,

I created a slidify presentation where in some slides I use <iframe> to load an html document, and in another slide I use shiny. The problem I have found is that if I  press knit HTML, the slides with the HTML documents are loaded, but no shiny slides show up, but if I use runDeck() the shiny app shows up, but the html is not found. Do you have a suggestion on how I can fix it.

**Comment by datalotpot786** [comment]
Hi Ramnath,

I have started using Slidify and really enjoying it. Is Shiny integration with Slidify is now good to be used. Can you share some examples of shiny  and slidify together (simple ones).

Thanks

Sandeep P.

**Comment by datalotpot786** [comment]
Ramnath, It appears shiny controls in slidify works only with runDeck() command. But this is not convinient as R studio and the Rmd has to be running. Is it not possible to have shiny control as part of html file? This way we can present the decks without R. Please let me know

Thanks
Sandeep

**Comment by nvramamoorthy** [comment]
I am recently learning slidify. 
> slidify(index.Rmd) 
creates .md file but not .html file.

I am getting following message 

> slidify("index.Rmd")


processing file: index.Rmd
  |.................................................................| 100%
  ordinary text without R code


output file: index.md

Error in if (body$content == "") { : 
  missing value where TRUE/FALSE needed
> 

Please suggest solution.

**Comment by ramnathv** [comment]
Try this.

```r
install.package('stringr')
if (packageVersion('stringr') > '1.0.0'){
 devtools::install_github('muschellij2/slidify')
} else {
  cat('You need stringr 1.0.0'
}
```

**Comment by lbarosi** [comment]
I just discovered slidify and I was so amazed with what I saw and read that I decided just to jump in.

Reality took me a step back:

I'm using R on Rstudio
Installed devtools and slidify from the dev branch
Opened the io2012 index.Rmd from the examples
In the R console, setwd to the index.Rmd dir
library(slidify)
library(slidifyLibraries)
slidify("index.Rmd")

and I got 
output file: index.md

```
Error in if (body$content == "") { : 
  valor ausente onde TRUE/FALSE necessário
```

Since I already read a lot here I load stringr with no result.

I inserted a parse_body function I found here, which brought me to a different error: "no md2html function found"
I found this on another thread:

```
md2html <- function(md){
  renderMarkdown(text = md,
                 renderer.options = c('hard_wrap'),
                 extensions = markdownExtensions()
  )
}
```

Then another error happened: "no such function renderMarkdow"
I found renderMarkdown function from Yihui but... problems with registeredRenderers

I know there should be some stupid mistake from me, but I really can't figure it out. Any help?
