### ISSUE TITLE
Error in markdownExtensions() while calling slidify()

### ISSUE THREAD

**Issue by AniMukherjee** [ramnathv/slidify#529]
Hello,

I'm new to R and Slidify package. I'm trying to follow the basic instructions. I installed required packages. but when I'm Knitting the Rmd document; I'm getting an error and the HTML is not getting created.

_> slidify('index.Rmd')

processing file: index.Rmd
                                                                                                 
output file: index.md

Error in markdownExtensions() : 
  could not find function "markdownExtensions"_

Please help me resolving this.

**Comment by AniMukherjee** [comment]
<img width="406" alt="image" src="https://user-images.githubusercontent.com/13029250/226843460-2538893a-edfc-4bd9-801a-46df9b452427.png">

**Comment by AniMukherjee** [comment]
I got the solution. So the R markdown library has modified a lot since late 2016 and currently does not support markdown Extension functions. I had to downgrade the package to get slidify working.

devtools::install_version("markdown", version = "0.5.2", repos = "http://cran.us.r-project.org")

**Comment by wieling** [comment]
There has been a change in one of the functions of markdown which causes the function renderMarkdown to not have the renderer.options parameter anymore (so far for backwards compatibility). Effectively, therefore, the function md2html in this source file fails: https://github.com/ramnathv/slidify/blob/master/R/utils.R

However, this can be fixed by executing the following command, after loading the slidify library:
assignInNamespace("md2html",md2html <- function(md){renderMarkdown(text = md)},ns="slidify") # fix
